# Generated by Django 5.0.2 on 2024-03-03 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=1000)),
                ('category', models.CharField(choices=[('Auto', 'Auto'), ('Clothing', 'Clothing'), ('Footwear', 'Footwear'), ('Accessories', 'Accessories'), ('Hobbies', 'Hobbies'), ('Pets', 'Pets'), ('Sale', 'Sale'), ('Services', 'Services'), ('Electronics', 'Electronics'), ('Children Goods', 'Children Goods'), ('Beauty and Health', 'Beauty Health'), ('Other', 'Other')], default='Other', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ad/images')),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ad.ad')),
            ],
        ),
    ]
